# permissions for end users to view etcdperves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: etcdperf-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: etcd-perf-operator
    app.kubernetes.io/part-of: etcd-perf-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdperf-viewer-role
rules:
- apiGroups:
  - etcd.redhat.com
  resources:
  - etcdperves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.redhat.com
  resources:
  - etcdperves/status
  verbs:
  - get
