apiVersion: etcd.redhat.com/v1
kind: EtcdPerf
metadata:
  labels:
    app.kubernetes.io/name: etcdperf
    app.kubernetes.io/instance: etcdperf-sample
    app.kubernetes.io/part-of: etcd-perf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-perf-operator
  name: etcdperf-sample
spec:
  # TODO(user): Add fields here
